### ISSUE TITLE
Push Source Code or Build Steps

### ISSUE THREAD

**Issue by marcbachmann** [CyanSalt/compiler-sfc#1]
I'd be interested in this module, but it looks weird that there's no source code at all for it. 🤔

**Comment by CyanSalt** [comment]
Sine the original [`@vue/compiler-sfc`](https://github.com/vuejs/vue/tree/main/packages/compiler-sfc) is highly coupled to vue itself, I tried to separate it but failed, so I chose to modify it directly based on the dist.

Although this is not feasible in the long run, given that vue@2 itself has stopped maintenance, I think it is acceptable to a certain extent.

**Comment by marcbachmann** [comment]
Thanks then 😄 
Might still try it out.
